# Generated by Django 4.0.4 on 2022-05-28 11:03

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('cin', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('dateBirth', models.DateField()),
                ('isDelete', models.DateTimeField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('cin', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('salary', models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('beginDate', models.DateField(blank=True, default=0)),
                ('endDate', models.DateField(blank=True, default=0)),
                ('role', models.CharField(max_length=20)),
                ('isDelete', models.DateTimeField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('availability', models.BooleanField(default=False)),
                ('isDelete', models.DateTimeField(default=0, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.user')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('bloodGroup', models.CharField(max_length=5)),
                ('height', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('allergy', models.CharField(blank=True, max_length=2000, null=True)),
                ('vaccination', models.CharField(max_length=2000)),
                ('healthInsurance', models.CharField(max_length=500)),
                ('isDelete', models.DateTimeField(default=0, null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 5, 28, 12, 3, 57, 137552))),
                ('paymentStatus', models.BooleanField(default=False)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('totalPaid', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('reason', models.CharField(max_length=1000)),
                ('prescription', models.CharField(max_length=2000)),
                ('isDelete', models.DateTimeField(default=0, null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.patient')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.user')),
            ],
        ),
    ]
