# Generated by Django 4.0.4 on 2022-05-28 11:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 12, 25, 23, 904004)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='isDelete',
            field=models.DateTimeField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.patient'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.user'),
        ),
        migrations.AlterField(
            model_name='medicalfile',
            name='isDelete',
            field=models.DateTimeField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='medicalfile',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='isDelete',
            field=models.DateTimeField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='isDelete',
            field=models.DateTimeField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='isDelete',
            field=models.DateTimeField(blank=True, default=0, null=True),
        ),
    ]
