# Generated by Django 4.0.4 on 2022-05-30 13:36

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_alter_appointment_date_alter_user_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 14, 36, 58, 541045)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='prescription',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='price',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='beginDate',
            field=models.DateField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='endDate',
            field=models.DateField(blank=True, default=0, null=True),
        ),
    ]
