# Generated by Django 4.0.4 on 2022-05-30 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0004_alter_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 14, 43, 18, 577131)),
        ),
        migrations.AlterField(
            model_name='medicalfile',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 14, 43, 18, 577131)),
        ),
    ]
