# Generated by Django 4.0.4 on 2022-06-25 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0005_alter_appointment_date_alter_medicalfile_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 25, 14, 24, 45, 186908)),
        ),
        migrations.AlterField(
            model_name='medicalfile',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 25, 14, 24, 45, 187908)),
        ),
    ]
