# Generated by Django 4.0.4 on 2022-06-25 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0006_patient_gender_alter_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 25, 14, 24, 56, 262925)),
        ),
        migrations.AlterField(
            model_name='medicalfile',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 25, 14, 24, 56, 263893)),
        ),
    ]
