# Generated by Django 4.0.4 on 2022-07-27 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0008_alter_appointment_date_alter_medicalfile_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='isDelete',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='medicalfile',
            name='isDelete',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='isDelete',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='isDelete',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='beginDate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='endDate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='isDelete',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
